// server/api/manga/index.get.ts

export default defineEventHandler((event) => {
    const allManga = [
        // Existing Manga (with full synopsis)
        { id: 1, title: 'Attack on Titan', author: 'Hajime Isayama', status: 'Finished', imageUrl: 'https://placehold.co/400x600/E8112D/white?text=Attack+on+Titan', genres: ['Action', 'Fantasy', 'Horror'], synopsis: 'In a world where humanity resides within enormous walls to protect themselves from giant man-eating humanoids known as Titans, a young boy vows to exterminate the Titans after they cause the destruction of his hometown.' },
        { id: 2, title: 'One-Punch Man', author: 'ONE', status: 'Ongoing', imageUrl: 'https://placehold.co/400x600/FFC800/white?text=One-Punch+Man', genres: ['Action', 'Comedy', 'Seinen'], synopsis: 'Follows the life of a hero who can defeat any enemy with a single punch, but seeks to find a worthy opponent after growing bored by a lack of challenge in his fight against evil.' },
        { id: 3, title: 'Berserk', author: 'Kentaro Miura', status: 'Hiatus', imageUrl: 'https://placehold.co/400x600/1C1C1C/white?text=Berserk', genres: ['Action', 'Fantasy', 'Seinen'], synopsis: 'Guts, a former mercenary now known as the "Black Swordsman," is out for revenge. A dark fantasy epic of struggle and destiny in a world filled with demons, nobles, and war.' },
        { id: 4, title: 'Jujutsu Kaisen', author: 'Gege Akutami', status: 'Ongoing', imageUrl: 'https://placehold.co/400x600/7B1FA2/white?text=Jujutsu+Kaisen', genres: ['Action', 'Fantasy', 'Supernatural'], synopsis: 'A boy swallows a cursed talisman - the finger of a demon - and becomes cursed himself. He enters a shaman\'s school to be able to locate the demon\'s other body parts and thus exorcise himself.' },
        { id: 5, title: 'Chainsaw Man', author: 'Tatsuki Fujimoto', status: 'Ongoing', imageUrl: 'https://placehold.co/400x600/FF4500/white?text=Chainsaw+Man', genres: ['Action', 'Seinen', 'Dark Fantasy'], synopsis: 'Following a betrayal, a young man left for dead is reborn as a powerful devil-human hybrid and is soon enlisted into an organization dedicated to hunting devils.' },
        { id: 6, title: 'Vinland Saga', author: 'Makoto Yukimura', status: 'Ongoing', imageUrl: 'https://placehold.co/400x600/8B4513/white?text=Vinland+Saga', genres: ['Action', 'Seinen', 'Historical'], synopsis: 'A young man named Thorfinn finds himself in a quest for revenge against the man who murdered his father. A story of vikings, vengeance, and the search for a peaceful land.' },
        { id: 7, title: 'Spy x Family', author: 'Tatsuya Endo', status: 'Ongoing', imageUrl: 'https://placehold.co/400x600/32CD32/white?text=Spy+x+Family', genres: ['Action', 'Comedy', 'Slice of Life'], synopsis: 'A spy on an undercover mission gets married and adopts a child, not realizing that his fake wife and daughter are an assassin and a telepath, respectively.' },
        { id: 8, title: 'Kaiju No. 8', author: 'Naoya Matsumoto', status: 'Ongoing', imageUrl: 'https://placehold.co/400x600/4682B4/white?text=Kaiju+No.+8', genres: ['Action', 'Fantasy', 'Sci-Fi'], synopsis: 'A man who is part of a crew that cleans up after giant monster attacks ingests a monster, gaining the ability to turn into one himself, code-named "Kaiju No. 8".' },
        { id: 9, title: 'Vagabond', author: 'Takehiko Inoue', status: 'Hiatus', imageUrl: 'https://placehold.co/400x600/A52A2A/white?text=Vagabond', genres: ['Action', 'Seinen', 'Historical'], synopsis: 'The fictionalized life of the legendary Japanese swordsman Miyamoto Musashi, chronicling his journey from a brash youth to an enlightened warrior.' },
        { id: 10, title: 'Grand Blue', author: 'Kenji Inoue', status: 'Ongoing', imageUrl: 'https://placehold.co/400x600/1E90FF/white?text=Grand+Blue', genres: ['Comedy', 'Seinen', 'Slice of Life'], synopsis: 'A college student looking forward to his ideal life in a seaside town gets roped into the antics of his university\'s eccentric, alcohol-fueled diving club.' },

        // New Manga Entries
        { id: 11, title: 'Demon Slayer', author: 'Koyoharu Gotouge', status: 'Finished', imageUrl: 'https://placehold.co/400x600/B22222/white?text=Demon+Slayer', genres: ['Action', 'Fantasy', 'Historical'], synopsis: 'A young boy becomes a demon slayer to avenge his family and cure his sister, who has turned into a demon, after a demon attack.' },
        { id: 12, title: 'My Hero Academia', author: 'Kōhei Horikoshi', status: 'Ongoing', imageUrl: 'https://placehold.co/400x600/008080/white?text=My+Hero+Academia', genres: ['Action', 'Superhero', 'Comedy'], synopsis: 'In a world where most people have superpowers, a boy born without them dreams of becoming the greatest hero. His life changes after he inherits the power of the world\'s number one hero.' },
        { id: 13, title: 'Kingdom', author: 'Yasuhisa Hara', status: 'Ongoing', imageUrl: 'https://placehold.co/400x600/DAA520/white?text=Kingdom', genres: ['Action', 'Seinen', 'Historical'], synopsis: 'In ancient China, two war orphans dream of becoming the greatest generals under the heavens. One\'s path leads him to the king, starting a journey to unify China.' },
        { id: 14, title: 'Blue Lock', author: 'Muneyuki Kaneshiro', status: 'Ongoing', imageUrl: 'https://placehold.co/400x600/0000CD/white?text=Blue+Lock', genres: ['Sports', 'Action'], synopsis: 'To create the world\'s greatest striker, the Japan Football Union initiates a radical project: Blue Lock, a prison-like facility where 300 of Japan\'s best young forwards are pitted against each other.' },
        { id: 15, title: 'Oshi no Ko', author: 'Aka Akasaka', status: 'Ongoing', imageUrl: 'https://placehold.co/400x600/FF69B4/white?text=Oshi+no+Ko', genres: ['Drama', 'Supernatural', 'Seinen'], synopsis: 'A doctor is reincarnated as the son of his favorite idol and navigates the dark side of the entertainment industry to uncover the truth behind her life and death.' },
        { id: 16, title: 'Frieren: Beyond Journey\'s End', author: 'Kanehito Yamada', status: 'Ongoing', imageUrl: 'https://placehold.co/400x600/ADD8E6/black?text=Frieren', genres: ['Fantasy', 'Adventure', 'Slice of Life'], synopsis: 'An elf mage, who outlives the rest of her heroic party, embarks on a new journey to understand humanity and the nature of time after her comrades pass away.' },
        { id: 17, title: 'Solo Leveling', author: 'Chugong', status: 'Finished', imageUrl: 'https://placehold.co/400x600/9400D3/white?text=Solo+Leveling', genres: ['Action', 'Fantasy', 'Webtoon'], synopsis: 'In a world of superpowered hunters and monsters, a notoriously weak hunter gains a unique ability to level up, embarking on a quest to become the strongest hunter alive.' },
        { id: 18, title: 'The Promised Neverland', author: 'Kaiu Shirai', status: 'Finished', imageUrl: 'https://placehold.co/400x600/F5DEB3/black?text=The+Promised+Neverland', genres: ['Mystery', 'Horror', 'Sci-Fi'], synopsis: 'A group of gifted orphans discover the horrifying truth behind their seemingly idyllic orphanage and must use their wits to orchestrate a desperate escape.' },
        { id: 19, title: 'Dr. Stone', author: 'Riichiro Inagaki', status: 'Finished', imageUrl: 'https://placehold.co/400x600/2E8B57/white?text=Dr.+Stone', genres: ['Adventure', 'Sci-Fi'], synopsis: 'Several thousand years after a mysterious phenomenon turned all of humanity to stone, a brilliant young scientist awakens and decides to rebuild civilization from scratch using the power of science.' },
        { id: 20, title: 'Haikyuu!!', author: 'Haruichi Furudate', status: 'Finished', imageUrl: 'https://placehold.co/400x600/FFA500/black?text=Haikyuu!!', genres: ['Sports', 'Comedy'], synopsis: 'Inspired by a short but formidable volleyball player, a young boy revives his school\'s volleyball club and vows to become a great player, despite his own short stature.' },
    ];

    // Updated categories to include the new manga
    return {
        trending: { title: 'Trending Now', items: allManga.filter(m => [2, 4, 5, 6, 12, 14, 15].includes(m.id)) },
        latestReleases: { title: 'New Releases', items: allManga.filter(m => [7, 8, 16].includes(m.id)) },
        popular: { title: 'Popular Titles', items: allManga.filter(m => [1, 3, 9, 10, 11, 13, 17].includes(m.id)) }
    }
})